// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import { SORTING_ORDER } from './queue-management';

export enum ITEM_SORTING_FIELD {
    IMPORT_DATE = 'IMPORT_DATE',
    TOTAL_AMOUNT = 'TOTAL_AMOUNT',
    USER_COUNTRY = 'USER_COUNTRY',
    PRODUCT_SKU = 'PRODUCT_SKU',
    SCORE = 'SCORE',
    ID = 'ID',
    ACTIVE = 'ACTIVE',
    QUEUE_IDS = 'QUEUE_IDS',
    LABEL_VALUE = 'LABEl_VALUE',
    TAGS = 'TAGS',
    LOCK_OWNER_ID = 'LOCK_OWNER_ID',
    HOLD_OWNER_ID = 'HOLD_OWNER_ID',
    LABEL_AUTHOR_ID = 'LABEL_AUTHOR_ID',
    LABEL_QUEUE_ID = 'LABEL_QUEUE_ID',
}

export const DEFAULT_SORTING = {
    field: ITEM_SORTING_FIELD.IMPORT_DATE,
    order: SORTING_ORDER.DESC,
};

export const ITEM_LIST_COLUMN_KEYS = {
    FRAUD_SCORE: ITEM_SORTING_FIELD.SCORE,
    ORDER_ID: 'ORDER_ID',
    QUEUES: 'QUEUES',
    TIME_LEFT: 'TIME_LEFT',
    IMPORT_DATE: ITEM_SORTING_FIELD.IMPORT_DATE,
    AMOUNT: ITEM_SORTING_FIELD.TOTAL_AMOUNT,
    STATUS: 'STATUS',
    ANALYST: ITEM_SORTING_FIELD.LABEL_AUTHOR_ID,
    TAGS: 'TAGS',
    NOTES: 'NOTES',
    ORIGINAL_ORDER_ID:'ORIGINAL_ORDER_ID'
};

export const AVAILABLE_SORTING_FIELDS = {
    [ITEM_LIST_COLUMN_KEYS.FRAUD_SCORE]: true,
    [ITEM_LIST_COLUMN_KEYS.IMPORT_DATE]: true,
    [ITEM_LIST_COLUMN_KEYS.AMOUNT]: true,
    [ITEM_LIST_COLUMN_KEYS.ANALYST]: true,
};
